### ISSUE TITLE
endsAt seems broken

### ISSUE THREAD

**Issue by srondal** [WAJUG/wajug.github.old.com#2]
When creating a new event for 2014, and endsAt is in 2013, I'd expect 2013 events to be hidden.
Or maybe its usage and behavior are not clear to me ;-)

**Comment by andypetrella** [comment]
Where do you expect them to be hidden? In the events page I guess.
If so, well, sounds good. My first idea for this was to create a separate
file for each year (as backups) and add a functionality to show previous
years ones...
I propose to start with this as a hack, then we'll see ;-)

**Comment by srondal** [comment]
Ideally past events should be archived and visible from another page, like a separate event page per year, as you suggest.
Of course in the meantime, they can simply be hidden, or even just stay there for the moment, not problematic at all.

**Comment by andypetrella** [comment]
done: I've created a talks-2013.json file and (almost) emptied the talks.json one... still need to create a backup page in the site ;-)
